namespace Ezzygate.Domain.Enums;

public enum TransactionSource
{
    Unknown = 0,
    ApprovalFee = 1,
    CcStorageFee = 2,
    ECheckFailedFee = 3,
    SystemCharge = 5,
    SystemRefund = 6,
    ManualChargeHebrew = 7,
    RemoteCharge = 8,
    PopupCharge = 9,
    AdminCharge = 10,
    PopupChargeHebrew = 11,
    PublicChargeHebrew = 12,
    IvrCharge = 14,
    HandCharge = 15,
    PhoneRefund = 16,
    ApprovedCharge = 17,
    ManualCharge = 18,
    PublicCharge = 19,
    Recurring = 20,
    MakingAPayment = 21,
    BatchFile = 22,
    PendingTransaction = 23,
    TestFromAdmin = 24,
    FailedFee = 25,
    DebitCards = 26,
    ChargeWithoutProcess = 27,
    RemoteChargeCcStorage = 28,
    AutoCapture = 29,
    AnnualFee = 30,
    MonthlyFee = 31,
    HostedPageV2He = 32,
    HostedPageV2En = 33,
    MobileWeb = 40,
    MobileApp = 41,
    WalletMobileApp = 42,
    MiniVt = 43,
    FraudFee = 50,
    UnitConversion = 51,
    ExcessiveChargebackFee = 52,
    WebApi = 53
}