namespace Ezzygate.Application.Configuration;

public interface IDomainConfiguration
{
    string Host { get; set; }
    string LegalName { get; set; }
    string BrandName { get; set; }
    string ShortCode { get; set; }
    string ThemeFolder { get; set; }
    string GoogleAnalytics { get; set; }
    string DataPath { get; set; }
    string PublicDataVirtualPath { get; set; }
    string CommonVirtualPath { get; set; }
    string CommonPhysicalPath { get; set; }
    int EncryptionKeyNumber { get; set; }
    string EzzygateAdminsNTGroupName { get; set; }
    string ServiceUser { get; set; }
    string ServiceUserPassword { get; set; }
    string WebApisMobileSecurityKey { get; set; }
    string WebApisMobileManualSecurityKey { get; set; }
    string WebApisMobileJwtSecretKey { get; set; }
    bool EnableEpa { get; set; }
    bool ForceSsl { get; set; }
    bool IsHebrewVisible { get; set; }
    bool SaveCui { get; set; }
    bool UsePublicPage { get; set; }
    bool MultiFactorAdmin { get; set; }
    bool DisablePostRedirectUrl { get; set; }
    string Sql1ConnectionString { get; set; }
    string Sql2ConnectionString { get; set; }
    string ReportsConnectionString { get; set; }
    string SqlArchiveConnectionString { get; set; }
    string AnalysisServicesConnectionString { get; set; }
    string IntegrationServicesReportsConnectionString { get; set; }
    string CrmConnectionString { get; set; }
    string MailNameFrom { get; set; }
    string MailAddressFrom { get; set; }
    string MailNameTo { get; set; }
    string MailAddressTo { get; set; }
    string MailAddressFromChb { get; set; }
    string SmtpHost { get; set; }
    string SmtpPort { get; set; }
    string SmtpUserName { get; set; }
    string SmtpPassword { get; set; }
    string SmsServiceProvider { get; set; }
    string SmsServiceUserName { get; set; }
    string SmsServicePassword { get; set; }
    string SmsServiceFrom { get; set; }
    string MerchantUrl { get; set; }
    string ReportsUrl { get; set; }
    string DevCenterUrl { get; set; }
    string ProcessUrl { get; set; }
    string ProcessV2Url { get; set; }
    string CartUrl { get; set; }
    string WalletUrl { get; set; }
    string WebServicesUrl { get; set; }
    string WebApiUrl { get; set; }
    string WebApiV2Url { get; set; }
    string PartnersUrl { get; set; }
    string ShopUrl { get; set; }
    string MiniVTUrl { get; set; }
    string AdminUrl { get; set; }
    string ContentUrl { get; set; }
    string WebsiteUrl { get; set; }
    string SignupUrl { get; set; }
    string SocialMediaFacebook { get; set; }
    string SocialMediaYoutube { get; set; }
    string SocialMediaLinkedIn { get; set; }
    string SocialMediaTwitter { get; set; }
    string CustomerServiceEmail { get; set; }
    string CustomerServiceSkype { get; set; }
    string CustomerServiceFax { get; set; }
    string CustomerServicePhone { get; set; }
    string CustomerServiceUSPhone { get; set; }
    string TechnicalSupportEmail { get; set; }
    string TechnicalSupportPhone { get; set; }
    string TechnicalSupportFax { get; set; }
    string TechnicalSupportSkype { get; set; }
    string IdentityAddress { get; set; }
    string IdentityCity { get; set; }
    string IdentityZipcode { get; set; }
    string IdentityCountry { get; set; }
    string CrmEmailTemplatePath { get; set; }
    string FinanceLevel1Group { get; set; }
    string FinanceLevel2Group { get; set; }
    string FraudDetectionAlertRecipients { get; set; }
    string FraudDetectionOperationMode { get; set; }
    string ActiveMerchantReportRecipients { get; set; }
    string BnsTransactionsWithoutEpaReportRecipients { get; set; }
    string IrregularityReportRecipients { get; set; }
    string DetectPhotocopyWithRefundRecipients { get; set; }
    string SettlementWalletAddress { get; set; }
    string FreshdeskApiKey { get; set; }
}